movies = [{'adult': False,
  'backdrop_path': '/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg',
  'genre_ids': [28, 53, 18],
  'id': 866398,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'The Beekeeper',
  'overview': 'One man’s campaign for vengeance takes on national stakes after '
              'he is revealed to be a former operative of a powerful and '
              'clandestine organization known as Beekeepers.',
  'popularity': 462.401,
  'poster_path': '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg',
  'release_date': '2024-01-10',
  'title': 'The Beekeeper',
  'video': ['https://www.youtube.com/watch?v=ZtcvVOknsAs',
            'https://www.youtube.com/watch?v=8ixwyQmYseY',
            'https://www.youtube.com/watch?v=FBwOSq2BdHI',
            'https://www.youtube.com/watch?v=qRolb_agd0k',
            'https://www.youtube.com/watch?v=pUeQbHlzlFc',
            'https://www.youtube.com/watch?v=BeRSDyVUuB4',
            'https://www.youtube.com/watch?v=rKbjzAl0rpg',
            'https://www.youtube.com/watch?v=EgMLz5B3K9w',
            'https://www.youtube.com/watch?v=VgWMNh8SPlg',
            'https://www.youtube.com/watch?v=SUNv4hYBY_U',
            'https://www.youtube.com/watch?v=AmTMdgvc_h8',
            'https://www.youtube.com/watch?v=QAxHoCA7dbw',
            'https://www.youtube.com/watch?v=QUCzcEz4FKw',
            'https://www.youtube.com/watch?v=dzIEH2jPZT8',
            'https://www.youtube.com/watch?v=CHKn-yDCE2w',
            'https://www.youtube.com/watch?v=dE0KFHYiQ4s',
            'https://www.youtube.com/watch?v=SzINZZ6iqxY'],
  'vote_average': 7.412,
  'vote_count': 239},
 {'adult': False,
  'backdrop_path': '/4gV6FOT4mEF4JaOmurO1kQSQ0Zl.jpg',
  'genre_ids': [28, 12, 14],
  'id': 572802,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Aquaman and the Lost Kingdom',
  'overview': "Black Manta, still driven by the need to avenge his father's "
              'death and wielding the power of the mythic Black Trident, will '
              'stop at nothing to take Aquaman down once and for all. To '
              'defeat him, Aquaman must turn to his imprisoned brother Orm, '
              'the former King of Atlantis, to forge an unlikely alliance in '
              'order to save the world from irreversible destruction.',
  'popularity': 6996.108,
  'poster_path': '/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg',
  'release_date': '2023-12-20',
  'title': 'Aquaman and the Lost Kingdom',
  'video': ['https://www.youtube.com/watch?v=41NUykFTZpQ',
            'https://www.youtube.com/watch?v=1dc1UycqDVk',
            'https://www.youtube.com/watch?v=Ix0gJwrpexI',
            'https://www.youtube.com/watch?v=PoF4B_xPVlg',
            'https://www.youtube.com/watch?v=_B25AduQRE4',
            'https://www.youtube.com/watch?v=zw5KVWAx_Ao',
            'https://www.youtube.com/watch?v=rgSZs3kVhKM',
            'https://www.youtube.com/watch?v=gB--kMMcrUY',
            'https://www.youtube.com/watch?v=Wk0cvHzpAIM',
            'https://www.youtube.com/watch?v=R6ZFWh6Utp0',
            'https://www.youtube.com/watch?v=4cSkHPW-MPE',
            'https://www.youtube.com/watch?v=UGc5Tzz19UY',
            'https://www.youtube.com/watch?v=Fbb4e_Q6wR8'],
  'vote_average': 6.991,
  'vote_count': 1130},
 {'adult': False,
  'backdrop_path': '/pWsD91G2R1Da3AKM3ymr3UoIfRb.jpg',
  'genre_ids': [28, 878, 18],
  'id': 933131,
  'media_type': 'movie',
  'original_language': 'ko',
  'original_title': '황야',
  'overview': 'After a deadly earthquake turns Seoul into a lawless badland, a '
              'fearless huntsman springs into action to rescue a teenager '
              'abducted by a mad doctor.',
  'popularity': 316.953,
  'poster_path': '/zVMyvNowgbsBAL6O6esWfRpAcOb.jpg',
  'release_date': '2024-01-26',
  'title': 'Badland Hunters',
  'video': ['https://www.youtube.com/watch?v=G82CgMekC5U',
            'https://www.youtube.com/watch?v=7u3zBVAxx_w',
            'https://www.youtube.com/watch?v=_OE7ApfhbC8'],
  'vote_average': 6.906,
  'vote_count': 80},
 {'adult': False,
  'backdrop_path': '/yOm993lsJyPmBodlYjgpPwBjXP9.jpg',
  'genre_ids': [35, 10751, 14],
  'id': 787699,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Wonka',
  'overview': 'Willy Wonka – chock-full of ideas and determined to change the '
              'world one delectable bite at a time – is proof that the best '
              'things in life begin with a dream, and if you’re lucky enough '
              'to meet Willy Wonka, anything is possible.',
  'popularity': 2783.603,
  'poster_path': '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
  'release_date': '2023-12-06',
  'title': 'Wonka',
  'video': ['https://www.youtube.com/watch?v=V5P7q4WJAzg',
            'https://www.youtube.com/watch?v=YkQVETRgaBc',
            'https://www.youtube.com/watch?v=AIytAE_X1zQ',
            'https://www.youtube.com/watch?v=vCcGYxy6PNA',
            'https://www.youtube.com/watch?v=Df1-tQ8IiDA',
            'https://www.youtube.com/watch?v=pkoqu0wZr_s',
            'https://www.youtube.com/watch?v=a1LcSbGRpIE',
            'https://www.youtube.com/watch?v=9Dup3jnovFs',
            'https://www.youtube.com/watch?v=JXIpIVelQkc',
            'https://www.youtube.com/watch?v=CsU0Yq6_LyQ',
            'https://www.youtube.com/watch?v=19bhnCBezs4',
            'https://www.youtube.com/watch?v=d2lVg-b_E2g',
            'https://www.youtube.com/watch?v=NiCEEIxI1ME',
            'https://www.youtube.com/watch?v=wYmtRhKvmVE',
            'https://www.youtube.com/watch?v=otNh9bTjXWg'],
  'vote_average': 7.3,
  'vote_count': 1649},
 {'adult': False,
  'backdrop_path': '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
  'genre_ids': [16, 10751, 14, 12],
  'id': 1022796,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Wish',
  'overview': 'Asha, a sharp-witted idealist, makes a wish so powerful that it '
              'is answered by a cosmic force – a little ball of boundless '
              'energy called Star. Together, Asha and Star confront a most '
              'formidable foe - the ruler of Rosas, King Magnifico - to save '
              'her community and prove that when the will of one courageous '
              'human connects with the magic of the stars, wondrous things can '
              'happen.',
  'popularity': 2033.084,
  'poster_path': '/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg',
  'release_date': '2023-11-13',
  'title': 'Wish',
  'video': ['https://www.youtube.com/watch?v=PIq5H5ctjnc',
            'https://www.youtube.com/watch?v=uK8ApZl3DNM',
            'https://www.youtube.com/watch?v=CPb9cSTorxw',
            'https://www.youtube.com/watch?v=NNS0IVinDCA',
            'https://www.youtube.com/watch?v=voNI4boN0wE',
            'https://www.youtube.com/watch?v=38TyKEZbkr0',
            'https://www.youtube.com/watch?v=wJ2UPmg1zLI',
            'https://www.youtube.com/watch?v=5tmuwCZyebY',
            'https://www.youtube.com/watch?v=82NbHdPVQCI',
            'https://www.youtube.com/watch?v=sXGuMfFk-eI',
            'https://www.youtube.com/watch?v=8a5SHQEhF6U',
            'https://www.youtube.com/watch?v=MKwYZ-mIWuE',
            'https://www.youtube.com/watch?v=dYYnNvSrfSU',
            'https://www.youtube.com/watch?v=JtTgzKIJT5o',
            'https://www.youtube.com/watch?v=8UTsDb5h9m4',
            'https://www.youtube.com/watch?v=whj1BVoiuxo',
            'https://www.youtube.com/watch?v=PburFAbTZnM',
            'https://www.youtube.com/watch?v=NaLQ1RpoFGY',
            'https://www.youtube.com/watch?v=Lyqhit860KM',
            'https://www.youtube.com/watch?v=pmFJ2GeLzac',
            'https://www.youtube.com/watch?v=5BCtEE0Ys7w',
            'https://www.youtube.com/watch?v=zoTFzeB29n0',
            'https://www.youtube.com/watch?v=YjY-w6CkVtM',
            'https://www.youtube.com/watch?v=pBXQiNY7p6A',
            'https://www.youtube.com/watch?v=KixZ-w3pQ9M',
            'https://www.youtube.com/watch?v=eQPeGiCH7A0',
            'https://www.youtube.com/watch?v=vgOhz3qk0c4',
            'https://www.youtube.com/watch?v=BHt7Otgx9-Y',
            'https://www.youtube.com/watch?v=syqFr82eM3Q',
            'https://www.youtube.com/watch?v=tOXC5kjsvss',
            'https://www.youtube.com/watch?v=jxKyVRfj948',
            'https://www.youtube.com/watch?v=rI5OR0Rx5zc',
            'https://www.youtube.com/watch?v=zIhJMpo-Z1U',
            'https://www.youtube.com/watch?v=oyRxxpD3yNw',
            'https://www.youtube.com/watch?v=ctlz0R1tSZE'],
  'vote_average': 6.637,
  'vote_count': 531},
 {'adult': False,
  'backdrop_path': '/nWLaQghS2v9jKGXFsl6M5y1UG3U.jpg',
  'genre_ids': [10751, 16, 35, 12],
  'id': 263109,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Shaun the Sheep Movie',
  'overview': 'When Shaun decides to take the day off and have some fun, he '
              'gets a little more action than he bargained for. A mix up with '
              'the Farmer, a caravan and a very steep hill lead them all to '
              "the Big City and it's up to Shaun and the flock to return "
              'everyone safely to the green grass of home.',
  'popularity': 34.017,
  'poster_path': '/dhVYlfMNc2bfXPB83LLL00I4l9n.jpg',
  'release_date': '2015-02-05',
  'title': 'Shaun the Sheep Movie',
  'video': ['https://www.youtube.com/watch?v=O_ZRKMaNIy0',
            'https://www.youtube.com/watch?v=E6qLSo9RsaE',
            'https://www.youtube.com/watch?v=zQHsXT_fxb4'],
  'vote_average': 7.007,
  'vote_count': 1292},
 {'adult': False,
  'backdrop_path': '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
  'genre_ids': [16, 12, 35, 10751, 28],
  'id': 940551,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Migration',
  'overview': 'After a migrating duck family alights on their pond with '
              'thrilling tales of far-flung places, the Mallard family embarks '
              'on a family road trip, from New England, to New York City, to '
              'tropical Jamaica.',
  'popularity': 1866.391,
  'poster_path': '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
  'release_date': '2023-12-06',
  'title': 'Migration',
  'video': ['https://www.youtube.com/watch?v=_8CbazcjJYw',
            'https://www.youtube.com/watch?v=D82bmMMyKAs',
            'https://www.youtube.com/watch?v=GMD7maD9K28',
            'https://www.youtube.com/watch?v=5GV2cbPHQhc',
            'https://www.youtube.com/watch?v=xhze2N1hYWU',
            'https://www.youtube.com/watch?v=HlNcqZKcpFc',
            'https://www.youtube.com/watch?v=JbX56fJTZvg',
            'https://www.youtube.com/watch?v=9VRvIkRrCck',
            'https://www.youtube.com/watch?v=NG0cx_HGJdc',
            'https://www.youtube.com/watch?v=vn_McNm1t9w',
            'https://www.youtube.com/watch?v=hWbfohXIdEU',
            'https://www.youtube.com/watch?v=UkHxhPGpRuA',
            'https://www.youtube.com/watch?v=cQfo0HJhCnE',
            'https://www.youtube.com/watch?v=m-4YnwBwaGk'],
  'vote_average': 7.836,
  'vote_count': 376},
 {'adult': False,
  'backdrop_path': '/h0oBqUpax591vOacpBsDJ8cynjk.jpg',
  'genre_ids': [878, 10749, 35],
  'id': 792307,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Poor Things',
  'overview': 'Brought back to life by an unorthodox scientist, a young woman '
              'runs off with a debauched lawyer on a whirlwind adventure '
              'across the continents. Free from the prejudices of her times, '
              'she grows steadfast in her purpose to stand for equality and '
              'liberation.',
  'popularity': 583.416,
  'poster_path': '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
  'release_date': '2023-12-07',
  'title': 'Poor Things',
  'video': ['https://www.youtube.com/watch?v=cpXyU2kZ2pM',
            'https://www.youtube.com/watch?v=gMd1tumz2zE',
            'https://www.youtube.com/watch?v=pPa5fup2x3k',
            'https://www.youtube.com/watch?v=02P3MWTSIQY',
            'https://www.youtube.com/watch?v=CFMLJ9tXxTs',
            'https://www.youtube.com/watch?v=Gf0r-Xzr35w',
            'https://www.youtube.com/watch?v=M0fT5zoixsU',
            'https://www.youtube.com/watch?v=SEBGdjkPtRo',
            'https://www.youtube.com/watch?v=8TJXpkDcBlQ',
            'https://www.youtube.com/watch?v=Rt1eClGhLMg',
            'https://www.youtube.com/watch?v=0H-u_MFnK5E',
            'https://www.youtube.com/watch?v=ohCrYZp_rVE',
            'https://www.youtube.com/watch?v=-EfYJWRw2FM',
            'https://www.youtube.com/watch?v=lO8OMtFirpQ',
            'https://www.youtube.com/watch?v=muuLGNH3JRQ',
            'https://www.youtube.com/watch?v=mb5P-WjE_Y8',
            'https://www.youtube.com/watch?v=S6hWqgxi0w4',
            'https://www.youtube.com/watch?v=YjwxH2z9_hY',
            'https://www.youtube.com/watch?v=hVx-v90MmMM',
            'https://www.youtube.com/watch?v=RlbR5N6veqw',
            'https://www.youtube.com/watch?v=ZFu7ZH4y6J4'],
  'vote_average': 8.192,
  'vote_count': 592},
 {'adult': False,
  'backdrop_path': '/mY3CRicUMaX3Btxv8yspud75UJu.jpg',
  'genre_ids': [35, 28, 80],
  'id': 848538,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Argylle',
  'overview': "When the plots of reclusive author Elly Conway's fictional "
              'espionage novels begin to mirror the covert actions of a '
              'real-life spy organization, quiet evenings at home become a '
              'thing of the past. Accompanied by her cat Alfie and Aiden, a '
              'cat-allergic spy, Elly races across the world to stay one step '
              "ahead of the killers as the line between Conway's fictional "
              'world and her real one begins to blur.',
  'popularity': 139.605,
  'poster_path': '/siduVKgOnABO4WH4lOwPQwaGwJp.jpg',
  'release_date': '2024-01-31',
  'title': 'Argylle',
  'video': ['https://www.youtube.com/watch?v=9UEJSbN3PWU',
            'https://www.youtube.com/watch?v=ToGDizBQE50',
            'https://www.youtube.com/watch?v=Sy6eNs3EW3E',
            'https://www.youtube.com/watch?v=fTbSAkMi-jo'],
  'vote_average': 7.7,
  'vote_count': 6},
 {'adult': False,
  'backdrop_path': '/dT1bXXEd7cfuVsB7CMvOKYiRZWl.jpg',
  'genre_ids': [35],
  'id': 1007826,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'The Underdoggs',
  'overview': "Jaycen 'Two Js' Jennings is a washed-up former pro football "
              'star who has hit rock bottom. When sentenced to community '
              'service coaching the Underdoggs, an unruly pee-wee football '
              'team in his hometown, he sees it mostly as an opportunity to '
              'rebuild his public image. But in the process, he may just turn '
              'his life around and rediscover his love of the game.',
  'popularity': 133.668,
  'poster_path': '/wj1VRcVsh39nkxLkZP8tuGd96tc.jpg',
  'release_date': '2024-01-25',
  'title': 'The Underdoggs',
  'video': ['https://www.youtube.com/watch?v=2PZ9f9i3WHs',
            'https://www.youtube.com/watch?v=MmfiqSJAou8'],
  'vote_average': 6.1,
  'vote_count': 14},
 {'adult': False,
  'backdrop_path': '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
  'genre_ids': [18, 36],
  'id': 872585,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Oppenheimer',
  'overview': "The story of J. Robert Oppenheimer's role in the development of "
              'the atomic bomb during World War II.',
  'popularity': 520.467,
  'poster_path': '/ptpr0kGAckfQkJeJIt8st5dglvd.jpg',
  'release_date': '2023-07-19',
  'title': 'Oppenheimer',
  'video': ['https://www.youtube.com/watch?v=hlZO437mwXQ',
            'https://www.youtube.com/watch?v=G_DMV5uYqfI',
            'https://www.youtube.com/watch?v=u6xoq-Xtr_U',
            'https://www.youtube.com/watch?v=kyXNephyqL0',
            'https://www.youtube.com/watch?v=qiuSBWVdgLI',
            'https://www.youtube.com/watch?v=0mSQo3z73Uk',
            'https://www.youtube.com/watch?v=kt4k8s1fVv4',
            'https://www.youtube.com/watch?v=oYNY8MM9ytg',
            'https://www.youtube.com/watch?v=KakdiNZ9Ssw',
            'https://www.youtube.com/watch?v=fU43oLToUTY',
            'https://www.youtube.com/watch?v=1xrBobulfJ4',
            'https://www.youtube.com/watch?v=D_uVhv5Dk3U',
            'https://www.youtube.com/watch?v=4iRwYGyBcmo',
            'https://www.youtube.com/watch?v=FWgOPGK589Q',
            'https://www.youtube.com/watch?v=7zYM550uw20',
            'https://www.youtube.com/watch?v=Dpo6QwdEkj0',
            'https://www.youtube.com/watch?v=jKsK0HJGQi0',
            'https://www.youtube.com/watch?v=mG5rlu6LTO0',
            'https://www.youtube.com/watch?v=0Q90x09QeWw',
            'https://www.youtube.com/watch?v=30mf5MGnc3g',
            'https://www.youtube.com/watch?v=RiHhQ8zc-UU',
            'https://www.youtube.com/watch?v=HkHWSvZUPy8',
            'https://www.youtube.com/watch?v=UdFeVo0cODs',
            'https://www.youtube.com/watch?v=e25RoI3rykw',
            'https://www.youtube.com/watch?v=-nlQtxwdfR4',
            'https://www.youtube.com/watch?v=qZCsZCyHFRM',
            'https://www.youtube.com/watch?v=pPG8TS23xR4',
            'https://www.youtube.com/watch?v=afaeQS_Lgcc',
            'https://www.youtube.com/watch?v=SJXNUJS5TU8',
            'https://www.youtube.com/watch?v=5ZYD-H4V2M0',
            'https://www.youtube.com/watch?v=Z98ojw6sK_w',
            'https://www.youtube.com/watch?v=sOsIKu2VAkM',
            'https://www.youtube.com/watch?v=wearzXv7WIE',
            'https://www.youtube.com/watch?v=l5QXphRn-TM',
            'https://www.youtube.com/watch?v=Y9EiLF7l8ug',
            'https://www.youtube.com/watch?v=jrMdXEtAse8',
            'https://www.youtube.com/watch?v=uYPbbksJxIg',
            'https://www.youtube.com/watch?v=bK6ldnjE3Y0'],
  'vote_average': 8.1,
  'vote_count': 6453},
 {'adult': False,
  'backdrop_path': '/du11oPPbEoDnUpiREO5tUg47rJd.jpg',
  'genre_ids': [18, 36],
  'id': 365620,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Ferrari',
  'overview': 'Set during the summer of 1957. Ex-racecar driver, Enzo Ferrari, '
              'is in crisis. Bankruptcy stalks the company he and his wife, '
              'Laura, built from nothing ten years earlier. Their tempestuous '
              'marriage struggles with the mourning for one son and the '
              'acknowledgement of another.',
  'popularity': 246.547,
  'poster_path': '/xBFyJHvXCTgf9Vmq5uCnXRHrMQ4.jpg',
  'release_date': '2023-12-14',
  'title': 'Ferrari',
  'video': ['https://www.youtube.com/watch?v=pHIywDJCKCM',
            'https://www.youtube.com/watch?v=PACCWdO2-So',
            'https://www.youtube.com/watch?v=ZpOKEr5luCs',
            'https://www.youtube.com/watch?v=E5-KQNySWiA',
            'https://www.youtube.com/watch?v=UkjfLhxWrjM',
            'https://www.youtube.com/watch?v=7gRFlOJLB_E',
            'https://www.youtube.com/watch?v=wPSNZ9_iRl4',
            'https://www.youtube.com/watch?v=P7AYHZYIfpY',
            'https://www.youtube.com/watch?v=OwdLLr1nFw4',
            'https://www.youtube.com/watch?v=HQSwG4WODhM',
            'https://www.youtube.com/watch?v=eUZ766ch51g',
            'https://www.youtube.com/watch?v=LoT0kYWJefY',
            'https://www.youtube.com/watch?v=IygqYbdfUTU',
            'https://www.youtube.com/watch?v=2y_3gGOzWa4',
            'https://www.youtube.com/watch?v=IfNTB6nHaME',
            'https://www.youtube.com/watch?v=KcY8L06J2ow',
            'https://www.youtube.com/watch?v=8oOVNMjM1Jk',
            'https://www.youtube.com/watch?v=zjVu-5mW1cA',
            'https://www.youtube.com/watch?v=AePkkp9WFOA',
            'https://www.youtube.com/watch?v=i-b68Ps33Jk',
            'https://www.youtube.com/watch?v=jGU4Cm5d0Zc',
            'https://www.youtube.com/watch?v=IsRTQB0CYuc',
            'https://www.youtube.com/watch?v=KZHxT2yb2cE'],
  'vote_average': 6.688,
  'vote_count': 264},
 {'adult': False,
  'backdrop_path': '/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg',
  'genre_ids': [878, 12, 28],
  'id': 609681,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'The Marvels',
  'overview': 'Carol Danvers, aka Captain Marvel, has reclaimed her identity '
              'from the tyrannical Kree and taken revenge on the Supreme '
              'Intelligence. But unintended consequences see Carol shouldering '
              'the burden of a destabilized universe. When her duties send her '
              'to an anomalous wormhole linked to a Kree revolutionary, her '
              'powers become entangled with that of Jersey City super-fan '
              'Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now '
              'S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this '
              'unlikely trio must team up and learn to work in concert to save '
              'the universe.',
  'popularity': 1664.558,
  'poster_path': '/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg',
  'release_date': '2023-11-08',
  'title': 'The Marvels',
  'video': ['https://www.youtube.com/watch?v=ZaTUatY-UoU',
            'https://www.youtube.com/watch?v=JoqRZFI7Z-s',
            'https://www.youtube.com/watch?v=6TGg0_xtLoA',
            'https://www.youtube.com/watch?v=ayeO1blP97M',
            'https://www.youtube.com/watch?v=8fTfj5pWU7Y',
            'https://www.youtube.com/watch?v=B4JVbM-UD-s',
            'https://www.youtube.com/watch?v=xD5799ubuNI',
            'https://www.youtube.com/watch?v=KwX963X5HWM',
            'https://www.youtube.com/watch?v=SwZELxTf1UU',
            'https://www.youtube.com/watch?v=uwmDH12MAA4',
            'https://www.youtube.com/watch?v=rcUO1OHg0gU',
            'https://www.youtube.com/watch?v=7-kbe9ucZxI',
            'https://www.youtube.com/watch?v=3tHAKPAb5YE',
            'https://www.youtube.com/watch?v=wg5liXvHl_Q',
            'https://www.youtube.com/watch?v=FCO08MSD-x0',
            'https://www.youtube.com/watch?v=mHEhxgx80fk',
            'https://www.youtube.com/watch?v=RVaKAYm96WE',
            'https://www.youtube.com/watch?v=p0A6GNACpRw',
            'https://www.youtube.com/watch?v=OC3lhUTFdZY',
            'https://www.youtube.com/watch?v=_jnMR2-zKoc',
            'https://www.youtube.com/watch?v=ZgBwHWlGAz0',
            'https://www.youtube.com/watch?v=3sHHCG1JDL8',
            'https://www.youtube.com/watch?v=wS_qbDztgVY',
            'https://www.youtube.com/watch?v=Zomcb-LKvgk',
            'https://www.youtube.com/watch?v=iuk77TjvfmE'],
  'vote_average': 6.4,
  'vote_count': 1323},
 {'adult': False,
  'backdrop_path': '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
  'genre_ids': [35, 12, 14],
  'id': 346698,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Barbie',
  'overview': 'Barbie and Ken are having the time of their lives in the '
              'colorful and seemingly perfect world of Barbie Land. However, '
              'when they get a chance to go to the real world, they soon '
              'discover the joys and perils of living among humans.',
  'popularity': 355.305,
  'poster_path': '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
  'release_date': '2023-07-19',
  'title': 'Barbie',
  'video': ['https://www.youtube.com/watch?v=0dgyWo4hATY',
            'https://www.youtube.com/watch?v=JnWXEUunzwM',
            'https://www.youtube.com/watch?v=SipXaLKcSu4',
            'https://www.youtube.com/watch?v=oBZ_ylYzBGI',
            'https://www.youtube.com/watch?v=-TP0wrslCEo',
            'https://www.youtube.com/watch?v=CBqlDWHkdHk',
            'https://www.youtube.com/watch?v=yBk1nKSerXs',
            'https://www.youtube.com/watch?v=aJuUO0ITk4U',
            'https://www.youtube.com/watch?v=zxOx2UCSzco',
            'https://www.youtube.com/watch?v=CZSJUyM21rw',
            'https://www.youtube.com/watch?v=c8ejR6qWVvM',
            'https://www.youtube.com/watch?v=EDOdCaj3R3s',
            'https://www.youtube.com/watch?v=_s0EOTN1XfU',
            'https://www.youtube.com/watch?v=rN5sjF3eDKc',
            'https://www.youtube.com/watch?v=LKglQMMG4aU',
            'https://www.youtube.com/watch?v=uHOWX4BmbH8',
            'https://www.youtube.com/watch?v=h_y8-295IB8',
            'https://www.youtube.com/watch?v=uQCM613pqY4',
            'https://www.youtube.com/watch?v=74Ie5QZC3Mc',
            'https://www.youtube.com/watch?v=KLqfVqDkXaI',
            'https://www.youtube.com/watch?v=Bcy3X57MSt0',
            'https://www.youtube.com/watch?v=vkoAEuR-SJQ',
            'https://www.youtube.com/watch?v=1ugNIPus_FU',
            'https://www.youtube.com/watch?v=wVDEuVefTvA',
            'https://www.youtube.com/watch?v=3CVkQ9T0O08',
            'https://www.youtube.com/watch?v=S0BJ8XOggmM',
            'https://www.youtube.com/watch?v=SpQowW39Ve8',
            'https://www.youtube.com/watch?v=k_29rmSGeEs',
            'https://www.youtube.com/watch?v=MeKVPM_VJcg',
            'https://www.youtube.com/watch?v=Y1IgAEejvqM',
            'https://www.youtube.com/watch?v=SvbYPrSQ4I8',
            'https://www.youtube.com/watch?v=RuZa7M9fsvE',
            'https://www.youtube.com/watch?v=lcnBEV5q8P4',
            'https://www.youtube.com/watch?v=ylYDgHFqmhw',
            'https://www.youtube.com/watch?v=7bGCbZnn6Uc',
            'https://www.youtube.com/watch?v=0BJi-Uhzqgk',
            'https://www.youtube.com/watch?v=35FbTkEXe2s',
            'https://www.youtube.com/watch?v=pBk4NYhWNMM',
            'https://www.youtube.com/watch?v=GRyt3Ov4zz0',
            'https://www.youtube.com/watch?v=8zIf0XvoL9Y'],
  'vote_average': 7.137,
  'vote_count': 7148},
 {'adult': False,
  'backdrop_path': '/fGe1ej335XbqN1j9teoDpofpbLX.jpg',
  'genre_ids': [18, 9648, 80],
  'id': 915935,
  'media_type': 'movie',
  'original_language': 'fr',
  'original_title': "Anatomie d'une chute",
  'overview': 'A woman is suspected of her husband’s murder, and their blind '
              'son faces a moral dilemma as the sole witness.',
  'popularity': 188.481,
  'poster_path': '/kQs6keheMwCxJxrzV83VUwFtHkB.jpg',
  'release_date': '2023-08-13',
  'title': 'Anatomy of a Fall',
  'video': ['https://www.youtube.com/watch?v=_4tp7QLgUZ0',
            'https://www.youtube.com/watch?v=AQ7XO8ceQSI',
            'https://www.youtube.com/watch?v=PvlKmNeRfbU',
            'https://www.youtube.com/watch?v=vtNYnjWUFqE',
            'https://www.youtube.com/watch?v=NEtX2WL_tKs',
            'https://www.youtube.com/watch?v=62p90Ta1H-Q',
            'https://www.youtube.com/watch?v=IvEhmdPgCgM',
            'https://www.youtube.com/watch?v=_MdTMA0PetA',
            'https://www.youtube.com/watch?v=auqWyjYfK7I',
            'https://www.youtube.com/watch?v=FUXawkH-ONM',
            'https://www.youtube.com/watch?v=fTrsp5BMloA'],
  'vote_average': 7.76,
  'vote_count': 788},
 {'adult': False,
  'backdrop_path': '/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg',
  'genre_ids': [28, 12, 53],
  'id': 891699,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Silent Night',
  'overview': 'A tormented father witnesses his young son die when caught in a '
              "gang's crossfire on Christmas Eve. While recovering from a "
              "wound that costs him his voice, he makes vengeance his life's "
              'mission and embarks on a punishing training regimen in order to '
              "avenge his son's death.",
  'popularity': 281.28,
  'poster_path': '/nJCP1ZNTPKlZ7S0Kv3gbmuraAT4.jpg',
  'release_date': '2023-11-30',
  'title': 'Silent Night',
  'video': ['https://www.youtube.com/watch?v=eKmEdwQLzoA',
            'https://www.youtube.com/watch?v=yBnTqn0lBDA'],
  'vote_average': 6.2,
  'vote_count': 362},
 {'adult': False,
  'backdrop_path': '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
  'genre_ids': [80, 36, 18],
  'id': 466420,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Killers of the Flower Moon',
  'overview': 'When oil is discovered in 1920s Oklahoma under Osage Nation '
              'land, the Osage people are murdered one by one—until the FBI '
              'steps in to unravel the mystery.',
  'popularity': 387.296,
  'poster_path': '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
  'release_date': '2023-10-18',
  'title': 'Killers of the Flower Moon',
  'video': ['https://www.youtube.com/watch?v=w733dXXp1T0',
            'https://www.youtube.com/watch?v=DAs4_R86W6g',
            'https://www.youtube.com/watch?v=YQ84YDAvYjM',
            'https://www.youtube.com/watch?v=H7v1VWy2gx4',
            'https://www.youtube.com/watch?v=ofERA2QBDzQ',
            'https://www.youtube.com/watch?v=pGVGws5b7UM',
            'https://www.youtube.com/watch?v=-wWq-PXG32c',
            'https://www.youtube.com/watch?v=pQzcjBXGnEU',
            'https://www.youtube.com/watch?v=1EYY8PL-ffM',
            'https://www.youtube.com/watch?v=HLWUK5Y7N5U',
            'https://www.youtube.com/watch?v=k6EjoZd-EgQ',
            'https://www.youtube.com/watch?v=tb1CygmjwNQ',
            'https://www.youtube.com/watch?v=6W9R46Rl2FE',
            'https://www.youtube.com/watch?v=qnklV7uamA8',
            'https://www.youtube.com/watch?v=5wWt8UHAff4',
            'https://www.youtube.com/watch?v=Lm73h0l1W2M',
            'https://www.youtube.com/watch?v=sTha2f-1Ivk',
            'https://www.youtube.com/watch?v=K-GBmleYQPw',
            'https://www.youtube.com/watch?v=3N1ZHtOMDMY',
            'https://www.youtube.com/watch?v=LqqAGyBGIo4',
            'https://www.youtube.com/watch?v=1oZUCkJEuvo',
            'https://www.youtube.com/watch?v=fAikmFIx19s',
            'https://www.youtube.com/watch?v=E1ybbfRpgG8',
            'https://www.youtube.com/watch?v=zEpokHwyYIg',
            'https://www.youtube.com/watch?v=dFhMUo_X7cg',
            'https://www.youtube.com/watch?v=cQBuZX1ourg',
            'https://www.youtube.com/watch?v=WAMzPTM2DTs',
            'https://www.youtube.com/watch?v=4GLbQyvT6-s',
            'https://www.youtube.com/watch?v=qKwHFiwvl1o',
            'https://www.youtube.com/watch?v=wIdbg6jD5B0',
            'https://www.youtube.com/watch?v=twP1tH9hfww',
            'https://www.youtube.com/watch?v=5tw1ctpDVg8',
            'https://www.youtube.com/watch?v=Dmqmva4L4rw',
            'https://www.youtube.com/watch?v=PVYVb7wqSZo',
            'https://www.youtube.com/watch?v=KSEmgcXoMW4',
            'https://www.youtube.com/watch?v=ehVqG84cYzo',
            'https://www.youtube.com/watch?v=vqTF_cdtu7I',
            'https://www.youtube.com/watch?v=Yb4mgjfs3Rs',
            'https://www.youtube.com/watch?v=n_zN0KKl7yI',
            'https://www.youtube.com/watch?v=3YuLJXRSn2k',
            'https://www.youtube.com/watch?v=myGT3mocWE0',
            'https://www.youtube.com/watch?v=4-Y3kBiq8qE',
            'https://www.youtube.com/watch?v=Or5vYmBzJsk',
            'https://www.youtube.com/watch?v=hemfPXxEfPY',
            'https://www.youtube.com/watch?v=DgWcqzBdmiQ',
            'https://www.youtube.com/watch?v=f1oqFhyjebw',
            'https://www.youtube.com/watch?v=EP34Yoxs3FQ',
            'https://www.youtube.com/watch?v=EG0si5bSd6I'],
  'vote_average': 7.537,
  'vote_count': 2173},
 {'adult': False,
  'backdrop_path': '/klb3yODwKMRle19EcvdeSatEZL7.jpg',
  'genre_ids': [27, 53],
  'id': 1072342,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Night Swim',
  'overview': 'Forced into early retirement by a degenerative illness, former '
              'baseball player Ray Waller moves into a new house with his wife '
              'and two children. He hopes that the backyard swimming pool will '
              'be fun for the kids and provide physical therapy for himself. '
              "However, a dark secret from the home's past soon unleashes a "
              'malevolent force that drags the family into the depths of '
              'inescapable terror.',
  'popularity': 279.676,
  'poster_path': '/gSkfBGdxdialBMM7P02V4hcI6Ij.jpg',
  'release_date': '2024-01-03',
  'title': 'Night Swim',
  'video': ['https://www.youtube.com/watch?v=J5IlZqB-vSc',
            'https://www.youtube.com/watch?v=WeoucJN98i4',
            'https://www.youtube.com/watch?v=R7LJ0IyUVnQ',
            'https://www.youtube.com/watch?v=5x-mnPN93to',
            'https://www.youtube.com/watch?v=PhlLO3Nb3sY',
            'https://www.youtube.com/watch?v=2qxsSGQz-zs'],
  'vote_average': 6.0,
  'vote_count': 153},
 {'adult': False,
  'backdrop_path': '/jR7ugO72zsNoNTIyt1iwlNP2qm4.jpg',
  'genre_ids': [16, 10751, 35, 12],
  'id': 519182,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Despicable Me 4',
  'overview': 'Gru and Lucy and their girls — Margo, Edith and Agnes — welcome '
              'a new member to the Gru family, Gru Jr., who is intent on '
              'tormenting his dad. Gru faces a new nemesis in Maxime Le Mal '
              'and his femme fatale girlfriend Valentina, and the family is '
              'forced to go on the run.',
  'popularity': 78.855,
  'poster_path': '/hoJDI4mkP2w9WK2po5aZx3YIcLP.jpg',
  'release_date': '2024-04-07',
  'title': 'Despicable Me 4',
  'video': ['https://www.youtube.com/watch?v=qQlr9-rF32A'],
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/uhUO7vQQKvCTfQWubOt5MAKokbL.jpg',
  'genre_ids': [12, 878],
  'id': 693134,
  'media_type': 'movie',
  'original_language': 'en',
  'original_title': 'Dune: Part Two',
  'overview': 'Follow the mythic journey of Paul Atreides as he unites with '
              'Chani and the Fremen while on a warpath of revenge against the '
              'conspirators who destroyed his family. Facing a choice between '
              'the love of his life and the fate of the known universe, Paul '
              'endeavors to prevent a terrible future only he can foresee.',
  'popularity': 115.661,
  'poster_path': '/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
  'release_date': '2024-02-28',
  'title': 'Dune: Part Two',
  'video': ['https://www.youtube.com/watch?v=VHa103ITb68',
            'https://www.youtube.com/watch?v=0QPxaoGh19I',
            'https://www.youtube.com/watch?v=136rl6tckGg',
            'https://www.youtube.com/watch?v=U2Qp5pL3ovA',
            'https://www.youtube.com/watch?v=_YUzQa_1RCE',
            'https://www.youtube.com/watch?v=Way9Dexny3w'],
  'vote_average': 0.0,
  'vote_count': 0}]